# Project: DEV_C++ 5.11
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = .//main.o .//RH_data.o .//RH_dsp.o .//RH_image.o .//RH_lib.o .//RH_math.o .//RH_utility.o
LINKOBJ  = .//main.o .//RH_data.o .//RH_dsp.o .//RH_image.o .//RH_lib.o .//RH_math.o .//RH_utility.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Personal/Desktop/Glucoo-Simulation-macOS"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "DEV_C++ 5.11.exe"
CXXFLAGS = $(CXXINCS) -g3 -std=c99
CFLAGS   = $(INCS) -g3 -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

.//main.o: main.c
	$(CC) -c main.c -o .//main.o $(CFLAGS)

.//RH_data.o: ../RH_data.c
	$(CC) -c ../RH_data.c -o .//RH_data.o $(CFLAGS)

.//RH_dsp.o: ../RH_dsp.c
	$(CC) -c ../RH_dsp.c -o .//RH_dsp.o $(CFLAGS)

.//RH_image.o: ../RH_image.c
	$(CC) -c ../RH_image.c -o .//RH_image.o $(CFLAGS)

.//RH_lib.o: ../RH_lib.c
	$(CC) -c ../RH_lib.c -o .//RH_lib.o $(CFLAGS)

.//RH_math.o: ../RH_math.c
	$(CC) -c ../RH_math.c -o .//RH_math.o $(CFLAGS)

.//RH_utility.o: ../RH_utility.c
	$(CC) -c ../RH_utility.c -o .//RH_utility.o $(CFLAGS)
